version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: userdb  # автоматично створюється userdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service-container
    ports:
      - "8081:8081"
    volumes:
      - ./build/libs:/app/libs
    networks:
      - app-network
    depends_on:
      - postgres-db
    restart: always

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
