version: '3'
services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service-container
    ports:
      - "0.0.0.0:8081:8081"
    volumes:
      - ./build/libs:/app/libs
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
